### ISSUE TITLE
InfiniteLoopDetector is false-positive on testing empty-output commands

### ISSUE THREAD

**Issue by wendigoxs** [hyperskill/hs-test#116]
There are could be CLI commands without any output for state mutating: filling database, complex calculation and so on.
But current v8 (hs-test:release-SNAPSHOT) ruins tests written and passed in hs-test:v7.2
E.g. SharedBillsSplitter https://hyperskill.org/projects/142

**Comment by aaaaaa2493** [comment]
Hi! Thank you for notifying us!

I disabled `InfiniteLoopDetector` in the SharedBillsSplitter's tests. If there are other projects that are affected by `InfiniteLoopDetector` feel free to report.
