### ISSUE TITLE
Optimization: Let’s use replace instead of replaceAll

### ISSUE THREAD

**Issue by rabestro** [hyperskill/hs-test#119]
https://github.com/hyperskill/hs-test/blob/5437461540644124acf234ca875667a8c4e5af7c/src/main/java/org/hyperskill/hstest/common/Utils.java#L43

1. String::replaceAll uses regular expression engine. In any cases where we need to replace regular string it is better to use String::replace.

2. `.replaceAll("\r\n", "\n").replaceAll("\r", "\n")` equals to `.replaceAll("\r\n?", "\n")`

**Comment by aaaaaa2493** [comment]
@rabestro Thanks! Then it's better to just use `replace` because we have the same line [in Python library](https://github.com/hyperskill/hs-test-python/blob/master/hstest/common/utils.py#L21-L26).

**Comment by aaaaaa2493** [comment]
Fixed in https://github.com/hyperskill/hs-test/commit/c31b45447bb6cebfae7607479fd4c5e157fe04d0
