### ISSUE TITLE
Gradle is not working with UTF-8 properly

### ISSUE THREAD

**Issue by aaaaaa2493** [hyperskill/hs-test#27]

**Comment by SerVB** [comment]
?

**Comment by aaaaaa2493** [comment]
![image](https://user-images.githubusercontent.com/20189630/57574809-96eb9680-7448-11e9-9127-87df9235ffc3.png)

![image](https://user-images.githubusercontent.com/20189630/57574815-9d7a0e00-7448-11e9-8ee6-a4afde7cfaea.png)

The solution is to paste the following inside `subprojects { ...  } ` of `build.gradle`
```gradle
compileJava.options.encoding = 'UTF-8'
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
```

but after that, there is still an error

![image](https://user-images.githubusercontent.com/20189630/57575105-4c204d80-744d-11e9-9c76-3ace9efb572c.png)

without gradle (clicking `Run test` inside idea) it works

The project is Maze Runner

**Comment by SerVB** [comment]
Maybe it's because you apply UTF-8 only for `compileJava`. Could you try adding the same for `compileTestJava`? I don't have Maze Runner tests now so I can't check it for myself.

By the way, I've been using this line for a while:

https://github.com/anonymous-frog-studio/pph/blob/d46446e6bc0ffadc327cc8d64eb60620adde5691/core/build.gradle#L4

**Comment by aaaaaa2493** [comment]
Thanks for the advice, I'll check this out

**Comment by aaaaaa2493** [comment]
Solved by adding this property:
```
test {
    systemProperty "file.encoding", "utf-8"
}
```

**Comment by SerVB** [comment]
And didn't my advice help? Just wondering :)

**Comment by aaaaaa2493** [comment]
Seems like.
```
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
```

Sets encoding for all of the tasks that depend on JavaCompile.

And `compileTestJava` task depends on `compileJava` task as you can see from the task dependence graph below.

![image](https://user-images.githubusercontent.com/20189630/58961387-a9d85900-87b1-11e9-8e7d-b2dd2ea579cf.png)
https://docs.gradle.org/current/userguide/java_plugin.html

So, your solution just shorthand of not working mine :) 
I tried it, but it didn't work.

This answer helped me if you're curious - https://stackoverflow.com/a/36932975
