### ISSUE TITLE
Prohibit using Asserts in tests

### ISSUE THREAD

**Issue by aaaaaa2493** [hyperskill/hs-test#32]
Need to catch `AssertionError` in `solve` method and raise `Fatal error`

**Comment by aaaaaa2493** [comment]
Updgaded:

1) Not `AssertionError` but any `Error`
2) Not in `solve` but in `generateTests` and `check`

**Comment by SerVB** [comment]
Why do you exclude `solve`? Example: `solve` has an invariant and it is checked by `assert`. And the invariant is written with a mistake and sometimes it fails. So the problem is in the `solve` method, it's a fatal error of the grader that should be sent to the team.

**Comment by aaaaaa2493** [comment]
There is a great chance that there would be no `solve` method in `v5` as `generatePredefinedInputOutput` and `checkSolved` as these methods serve a little purpose but complicate things a lot.

**Comment by SerVB** [comment]
Finally got it! Great plans to remove these methods, by the way :)
